insert into books (name, summary, author_id, gender_id, year) values ('Stuart: A Life Backward', 'Aluminum', 89, 3, 1986);
insert into books (name, summary, author_id, gender_id, year) values ('Oliver!', 'Vinyl', 37, 4, 1998);
insert into books (name, summary, author_id, gender_id, year) values ('Wrestling Ernest Hemingway', 'Aluminum', 35, 2, 1978);
insert into books (name, summary, author_id, gender_id, year) values ('Goddess (Devi)', 'Steel', 97, 4, 2023);
insert into books (name, summary, author_id, gender_id, year) values ('Charlotte''s Web', 'Granite', 27, 4, 1930);
insert into books (name, summary, author_id, gender_id, year) values ('Cosmic Psychos: Blokes You Can Trust', 'Glass', 6, 1, 2021);
insert into books (name, summary, author_id, gender_id, year) values ('Lightspeed', 'Granite', 93, 4, 1961);
insert into books (name, summary, author_id, gender_id, year) values ('Witches, The (Le streghe)', 'Aluminum', 88, 2, 1995);
insert into books (name, summary, author_id, gender_id, year) values ('Shape of Things, The', 'Brass', 88, 4, 2016);
insert into books (name, summary, author_id, gender_id, year) values ('Die Fighting', 'Glass', 61, 4, 1987);
insert into books (name, summary, author_id, gender_id, year) values ('Eye of the Devil', 'Stone', 52, 3, 1942);
insert into books (name, summary, author_id, gender_id, year) values ('Diaries Notes and Sketches (Walden)', 'Wood', 77, 2, 1964);
insert into books (name, summary, author_id, gender_id, year) values ('Child''s Christmas in Wales, A', 'Steel', 99, 3, 1954);
insert into books (name, summary, author_id, gender_id, year) values ('Black Bread (Pa Negre)', 'Rubber', 73, 1, 1974);
insert into books (name, summary, author_id, gender_id, year) values ('Notre jour viendra', 'Vinyl', 55, 2, 2005);
insert into books (name, summary, author_id, gender_id, year) values ('Main Event, The', 'Stone', 64, 3, 2015);
insert into books (name, summary, author_id, gender_id, year) values ('Failure to Launch', 'Vinyl', 64, 3, 1947);
insert into books (name, summary, author_id, gender_id, year) values ('Tin Man', 'Stone', 45, 4, 1961);
insert into books (name, summary, author_id, gender_id, year) values ('Last Casino, The', 'Granite', 16, 2, 2009);
insert into books (name, summary, author_id, gender_id, year) values ('Memphis Belle: A Story of a Flying Fortress, The', 'Plastic', 23, 4, 1937);
insert into books (name, summary, author_id, gender_id, year) values ('Resident Evil: Degeneration (Baiohazâdo: Dijenerêshon)', 'Wood', 89, 3, 1976);
insert into books (name, summary, author_id, gender_id, year) values ('Mighty Peking Man (a.k.a. Goliathon) (Xing xing wang)', 'Plexiglass', 71, 4, 1967);
insert into books (name, summary, author_id, gender_id, year) values ('Mad Hot Ballroom', 'Aluminum', 22, 4, 1975);
insert into books (name, summary, author_id, gender_id, year) values ('Aziz Ansari: Intimate Moments for a Sensual Evening', 'Wood', 27, 3, 1965);
insert into books (name, summary, author_id, gender_id, year) values ('Undisputed III: Redemption', 'Brass', 2, 3, 1975);
insert into books (name, summary, author_id, gender_id, year) values ('Devil Times Five (a.k.a. Peopletoys)', 'Rubber', 6, 3, 1947);
insert into books (name, summary, author_id, gender_id, year) values ('Rogue Cop', 'Plastic', 33, 1, 1960);
insert into books (name, summary, author_id, gender_id, year) values ('Blue Collar', 'Aluminum', 59, 1, 1967);
insert into books (name, summary, author_id, gender_id, year) values ('Yuva', 'Plexiglass', 73, 4, 1960);
insert into books (name, summary, author_id, gender_id, year) values ('Freeway', 'Glass', 40, 4, 2008);
insert into books (name, summary, author_id, gender_id, year) values ('Bang Boom Bang - Ein todsicheres Ding', 'Granite', 21, 1, 2022);
insert into books (name, summary, author_id, gender_id, year) values ('How Tasty Was My Little Frenchman (Como Era Gostoso o Meu Francês)', 'Steel', 17, 3, 1966);
insert into books (name, summary, author_id, gender_id, year) values ('Voyager (Homo Faber)', 'Brass', 59, 2, 1996);
insert into books (name, summary, author_id, gender_id, year) values ('Stacy''s Knights', 'Steel', 7, 4, 2018);
insert into books (name, summary, author_id, gender_id, year) values ('Roger Dodger', 'Steel', 80, 3, 1999);
insert into books (name, summary, author_id, gender_id, year) values ('Touch of Pink', 'Glass', 79, 4, 1948);
insert into books (name, summary, author_id, gender_id, year) values ('Sebastian Maniscalco: What''s Wrong with People?', 'Rubber', 84, 4, 2022);
insert into books (name, summary, author_id, gender_id, year) values ('Spriggan (Supurigan)', 'Wood', 95, 4, 1955);
insert into books (name, summary, author_id, gender_id, year) values ('Belle comme la femme d''un autre', 'Plastic', 15, 3, 1998);
insert into books (name, summary, author_id, gender_id, year) values ('One Husband Too Many', 'Rubber', 55, 2, 2017);
insert into books (name, summary, author_id, gender_id, year) values ('With Great Power: The Stan Lee Story', 'Vinyl', 16, 3, 1961);
insert into books (name, summary, author_id, gender_id, year) values ('Wuthering Heights', 'Plexiglass', 51, 4, 1945);
insert into books (name, summary, author_id, gender_id, year) values ('Corto Maltese: Under the Sign of Capricorn (Sous le signe du capricorne)', 'Steel', 93, 4, 1950);
insert into books (name, summary, author_id, gender_id, year) values ('Phantom of Liberty, The (Fantôme de la liberté, Le)', 'Stone', 84, 3, 1934);
insert into books (name, summary, author_id, gender_id, year) values ('Plans for Tomorrow (Planes para mañana)', 'Aluminum', 90, 1, 1988);
insert into books (name, summary, author_id, gender_id, year) values ('Thunder Soul', 'Stone', 91, 2, 2017);
insert into books (name, summary, author_id, gender_id, year) values ('Love and Sex under Nazi Occupation (Amour et sexe sous l''occupation) ', 'Plastic', 11, 4, 1967);
insert into books (name, summary, author_id, gender_id, year) values ('Carried Away', 'Wood', 83, 4, 1981);
insert into books (name, summary, author_id, gender_id, year) values ('Backlight', 'Rubber', 50, 4, 1978);
insert into books (name, summary, author_id, gender_id, year) values ('Long Walk Home, The', 'Wood', 64, 3, 1970);
insert into books (name, summary, author_id, gender_id, year) values ('Taste of Tea, The (Cha no aji)', 'Plastic', 38, 4, 2017);
insert into books (name, summary, author_id, gender_id, year) values ('Turning Tide (En solitaire)', 'Plexiglass', 1, 4, 2003);
insert into books (name, summary, author_id, gender_id, year) values ('Clandestine Childhood', 'Brass', 80, 1, 1987);
insert into books (name, summary, author_id, gender_id, year) values ('The Reunion', 'Wood', 8, 1, 1972);
insert into books (name, summary, author_id, gender_id, year) values ('Beslan: Three Days in September', 'Brass', 13, 4, 1933);
insert into books (name, summary, author_id, gender_id, year) values ('Hills Have Eyes, The', 'Rubber', 85, 3, 1969);
insert into books (name, summary, author_id, gender_id, year) values ('Take Aim at the Police Van (Sono gosôsha wo nerae: ''Jûsangô taihisen'' yori)', 'Stone', 14, 3, 1952);
insert into books (name, summary, author_id, gender_id, year) values ('Sherlock Holmes', 'Plastic', 93, 1, 2014);
insert into books (name, summary, author_id, gender_id, year) values ('Cloudland', 'Vinyl', 100, 2, 1972);
insert into books (name, summary, author_id, gender_id, year) values ('Dead & Buried', 'Glass', 48, 2, 2016);
insert into books (name, summary, author_id, gender_id, year) values ('Seed', 'Brass', 29, 4, 1937);
insert into books (name, summary, author_id, gender_id, year) values ('Scarlet Empress, The', 'Plexiglass', 7, 3, 1992);
insert into books (name, summary, author_id, gender_id, year) values ('Sunset Strip', 'Granite', 43, 4, 2021);
insert into books (name, summary, author_id, gender_id, year) values ('Once Upon a Time (Der var engang)', 'Glass', 30, 1, 1936);
insert into books (name, summary, author_id, gender_id, year) values ('Failan', 'Plexiglass', 65, 2, 2024);
insert into books (name, summary, author_id, gender_id, year) values ('When Marnie Was There', 'Rubber', 77, 1, 1946);
insert into books (name, summary, author_id, gender_id, year) values ('Fist of the North Star', 'Plexiglass', 39, 1, 1961);
insert into books (name, summary, author_id, gender_id, year) values ('Riki-Oh: The Story of Ricky (Lik Wong)', 'Aluminum', 13, 1, 1975);
insert into books (name, summary, author_id, gender_id, year) values ('Body/Cialo', 'Brass', 42, 4, 1947);
insert into books (name, summary, author_id, gender_id, year) values ('Crumb', 'Aluminum', 46, 4, 2005);
insert into books (name, summary, author_id, gender_id, year) values ('Dry Season (Daratt)', 'Plastic', 22, 2, 1966);
insert into books (name, summary, author_id, gender_id, year) values ('Lucky Star', 'Steel', 44, 3, 1985);
insert into books (name, summary, author_id, gender_id, year) values ('Laws of Attraction', 'Rubber', 47, 1, 2001);
insert into books (name, summary, author_id, gender_id, year) values ('Mr. Blandings Builds His Dream House', 'Steel', 46, 3, 2014);
insert into books (name, summary, author_id, gender_id, year) values ('I.Q.', 'Plastic', 69, 4, 1955);
insert into books (name, summary, author_id, gender_id, year) values ('Café de Flore', 'Stone', 40, 4, 1932);
insert into books (name, summary, author_id, gender_id, year) values ('Return of Mod Squad, The', 'Plastic', 60, 4, 1984);
insert into books (name, summary, author_id, gender_id, year) values ('Shaolin Wooden Men (Shao Lin mu ren xiang)', 'Vinyl', 61, 3, 1985);
insert into books (name, summary, author_id, gender_id, year) values ('She Wouldn''t Say Yes', 'Stone', 48, 3, 2020);
insert into books (name, summary, author_id, gender_id, year) values ('Bay of Blood (a.k.a. Twitch of the Death Nerve) (Reazione a catena)', 'Vinyl', 30, 3, 2007);
insert into books (name, summary, author_id, gender_id, year) values ('Perfect Man, The', 'Aluminum', 64, 3, 1970);
insert into books (name, summary, author_id, gender_id, year) values ('Trishna', 'Stone', 19, 4, 1946);
insert into books (name, summary, author_id, gender_id, year) values ('Just Like Heaven', 'Wood', 9, 1, 2013);
insert into books (name, summary, author_id, gender_id, year) values ('Blair Witch Project, The', 'Aluminum', 88, 3, 1968);
insert into books (name, summary, author_id, gender_id, year) values ('Neurons to Nirvana', 'Granite', 12, 1, 1976);
insert into books (name, summary, author_id, gender_id, year) values ('8 Seconds', 'Plexiglass', 45, 2, 1954);
insert into books (name, summary, author_id, gender_id, year) values ('Student of the Year', 'Wood', 27, 3, 1938);
insert into books (name, summary, author_id, gender_id, year) values ('Zone Troopers', 'Plexiglass', 65, 3, 1945);
insert into books (name, summary, author_id, gender_id, year) values ('Paper Will Be Blue, The (Hîrtia va fi albastrã)', 'Wood', 100, 1, 1944);
insert into books (name, summary, author_id, gender_id, year) values ('Oculus', 'Glass', 38, 2, 1987);
insert into books (name, summary, author_id, gender_id, year) values ('About Time', 'Steel', 82, 4, 1932);
insert into books (name, summary, author_id, gender_id, year) values ('I Shot Andy Warhol', 'Plexiglass', 28, 1, 1977);
insert into books (name, summary, author_id, gender_id, year) values ('Bride of the Wind', 'Aluminum', 90, 4, 1993);
insert into books (name, summary, author_id, gender_id, year) values ('Tintin and I', 'Wood', 63, 3, 2005);
insert into books (name, summary, author_id, gender_id, year) values ('Man with the Gun', 'Steel', 2, 3, 1974);
insert into books (name, summary, author_id, gender_id, year) values ('Out of Bounds', 'Rubber', 16, 2, 2023);
insert into books (name, summary, author_id, gender_id, year) values ('Promised Life, The (Vie promise, La)', 'Granite', 3, 4, 1982);
insert into books (name, summary, author_id, gender_id, year) values ('Get Low', 'Rubber', 56, 3, 1960);
insert into books (name, summary, author_id, gender_id, year) values ('Messenger, The', 'Aluminum', 5, 3, 1933);
insert into books (name, summary, author_id, gender_id, year) values ('Chairman of the Board', 'Vinyl', 33, 1, 1998);
insert into books (name, summary, author_id, gender_id, year) values ('I''m Not Scared (Io non ho paura)', 'Plexiglass', 74, 2, 1945);
insert into books (name, summary, author_id, gender_id, year) values ('Tom and Jerry: The Movie', 'Wood', 17, 2, 1936);
insert into books (name, summary, author_id, gender_id, year) values ('Lonely Passion of Judith Hearne, The', 'Granite', 1, 1, 2017);
insert into books (name, summary, author_id, gender_id, year) values ('Fireman, The', 'Wood', 57, 1, 1979);
insert into books (name, summary, author_id, gender_id, year) values ('Long, Hot Summer, The', 'Brass', 79, 3, 2004);
insert into books (name, summary, author_id, gender_id, year) values ('Price Above Rubies, A', 'Steel', 11, 3, 1995);
insert into books (name, summary, author_id, gender_id, year) values ('John Dies at the End', 'Brass', 51, 4, 1977);
insert into books (name, summary, author_id, gender_id, year) values ('Personal History, Adventures, Experience, & Observation of David Copperfield the Younger, The (a.k.a. David Copperfield)', 'Aluminum', 21, 2, 1959);
insert into books (name, summary, author_id, gender_id, year) values ('Secret Ballot (Raye makhfi)', 'Glass', 98, 3, 1955);
insert into books (name, summary, author_id, gender_id, year) values ('Godzilla and Mothra: The Battle for Earth (Gojira vs. Mosura)', 'Rubber', 89, 2, 1989);
insert into books (name, summary, author_id, gender_id, year) values ('Time to Live, a Time to Die, A (Tong nien wang shi)', 'Granite', 8, 4, 1967);
insert into books (name, summary, author_id, gender_id, year) values ('Shooting Fish', 'Plexiglass', 65, 2, 2017);
insert into books (name, summary, author_id, gender_id, year) values ('Diabolique (Les diaboliques)', 'Glass', 56, 2, 1992);
insert into books (name, summary, author_id, gender_id, year) values ('The Underneath', 'Steel', 58, 1, 1979);
insert into books (name, summary, author_id, gender_id, year) values ('Silja - nuorena nukkunut', 'Brass', 13, 1, 1983);
insert into books (name, summary, author_id, gender_id, year) values ('Charlie Chan at the Race Track', 'Plexiglass', 40, 4, 1996);
insert into books (name, summary, author_id, gender_id, year) values ('Running Free', 'Vinyl', 88, 2, 1943);
insert into books (name, summary, author_id, gender_id, year) values ('Hawking', 'Granite', 11, 1, 2020);
insert into books (name, summary, author_id, gender_id, year) values ('War Game, The', 'Glass', 94, 4, 1995);
insert into books (name, summary, author_id, gender_id, year) values ('Child''s Play 3', 'Plexiglass', 9, 2, 1978);
insert into books (name, summary, author_id, gender_id, year) values ('Field of Dreams', 'Glass', 86, 1, 2006);
insert into books (name, summary, author_id, gender_id, year) values ('Paper Soldier (Bumazhnyy soldat)', 'Wood', 92, 4, 1959);
insert into books (name, summary, author_id, gender_id, year) values ('Fail Safe', 'Stone', 34, 4, 2013);
insert into books (name, summary, author_id, gender_id, year) values ('Journey to the West: Conquering the Demons (Daai wa sai you chi Chui mo chun kei)', 'Plexiglass', 65, 4, 1954);
insert into books (name, summary, author_id, gender_id, year) values ('High Cost of Living, The', 'Glass', 53, 3, 1995);
insert into books (name, summary, author_id, gender_id, year) values ('Richie Rich', 'Granite', 94, 1, 1985);
insert into books (name, summary, author_id, gender_id, year) values ('Play the Game', 'Rubber', 16, 3, 1981);
insert into books (name, summary, author_id, gender_id, year) values ('Dagon', 'Wood', 96, 4, 1995);
insert into books (name, summary, author_id, gender_id, year) values ('8MM', 'Plastic', 52, 1, 2005);
insert into books (name, summary, author_id, gender_id, year) values ('Unfinished Business', 'Rubber', 55, 1, 1950);
insert into books (name, summary, author_id, gender_id, year) values ('Cookers', 'Wood', 14, 1, 2005);
insert into books (name, summary, author_id, gender_id, year) values ('Mona Lisa', 'Aluminum', 4, 1, 2019);
insert into books (name, summary, author_id, gender_id, year) values ('Def-Con 4', 'Plastic', 23, 2, 2015);
insert into books (name, summary, author_id, gender_id, year) values ('In a Year with 13 Moons (In einem Jahr mit 13 Monden)', 'Granite', 56, 1, 1956);
insert into books (name, summary, author_id, gender_id, year) values ('Choppertown: The Sinners', 'Brass', 6, 2, 2005);
insert into books (name, summary, author_id, gender_id, year) values ('Broom-Stick Bunny', 'Granite', 11, 2, 1937);
insert into books (name, summary, author_id, gender_id, year) values ('This Special Friendship (Les amitiés particulières)', 'Vinyl', 14, 3, 1995);
insert into books (name, summary, author_id, gender_id, year) values ('Grave, The', 'Wood', 95, 1, 1940);
insert into books (name, summary, author_id, gender_id, year) values ('Holy Man', 'Glass', 64, 3, 1989);
insert into books (name, summary, author_id, gender_id, year) values ('Double Life of Veronique, The (Double Vie de Véronique, La)', 'Aluminum', 75, 1, 1959);
insert into books (name, summary, author_id, gender_id, year) values ('Nightmare on Elm Street 5: The Dream Child, A', 'Glass', 28, 2, 1966);
insert into books (name, summary, author_id, gender_id, year) values ('Nine Queens (Nueve reinas)', 'Granite', 15, 3, 1951);
insert into books (name, summary, author_id, gender_id, year) values ('Noah', 'Aluminum', 99, 3, 2008);
insert into books (name, summary, author_id, gender_id, year) values ('Deja Vu', 'Stone', 83, 2, 2005);
insert into books (name, summary, author_id, gender_id, year) values ('Last Dragon, The', 'Rubber', 54, 1, 1985);
insert into books (name, summary, author_id, gender_id, year) values ('Last Days in the Desert', 'Glass', 77, 4, 1933);
insert into books (name, summary, author_id, gender_id, year) values ('Place in the Sun, A', 'Stone', 24, 3, 1998);
insert into books (name, summary, author_id, gender_id, year) values ('Soldier''s Plaything, A', 'Wood', 91, 4, 2013);
insert into books (name, summary, author_id, gender_id, year) values ('Hercules and the Lost Kingdom', 'Wood', 14, 3, 1930);
insert into books (name, summary, author_id, gender_id, year) values ('Too Many Cooks', 'Wood', 81, 2, 2020);
insert into books (name, summary, author_id, gender_id, year) values ('Fire in the Blood', 'Brass', 75, 3, 1930);
insert into books (name, summary, author_id, gender_id, year) values ('Torpedo Run', 'Plexiglass', 95, 4, 1962);
insert into books (name, summary, author_id, gender_id, year) values ('Cathy Come Home', 'Vinyl', 73, 4, 2010);
insert into books (name, summary, author_id, gender_id, year) values ('City of Ember', 'Granite', 82, 1, 1978);
insert into books (name, summary, author_id, gender_id, year) values ('Babylon XX', 'Steel', 19, 1, 2014);
insert into books (name, summary, author_id, gender_id, year) values ('Cinderella Man', 'Rubber', 30, 2, 1972);
insert into books (name, summary, author_id, gender_id, year) values ('Hey, Happy!', 'Steel', 94, 4, 1932);
insert into books (name, summary, author_id, gender_id, year) values ('It''s Alive', 'Wood', 8, 3, 1941);
insert into books (name, summary, author_id, gender_id, year) values ('War of the Wildcats (In Old Oklahoma)', 'Vinyl', 33, 1, 1958);
insert into books (name, summary, author_id, gender_id, year) values ('Drunks', 'Vinyl', 65, 2, 1989);
insert into books (name, summary, author_id, gender_id, year) values ('Dilemma, The', 'Glass', 27, 3, 1975);
insert into books (name, summary, author_id, gender_id, year) values ('Gnome-Mobile, The', 'Glass', 77, 4, 1956);
insert into books (name, summary, author_id, gender_id, year) values ('Cheyenne Social Club, The', 'Plexiglass', 74, 4, 1963);
insert into books (name, summary, author_id, gender_id, year) values ('Red Rock West', 'Brass', 62, 3, 1986);
insert into books (name, summary, author_id, gender_id, year) values ('Champ, The', 'Plexiglass', 5, 4, 1947);
insert into books (name, summary, author_id, gender_id, year) values ('Ox-Bow Incident, The', 'Aluminum', 99, 3, 1958);
insert into books (name, summary, author_id, gender_id, year) values ('Hello, Dolly!', 'Steel', 63, 4, 2006);
insert into books (name, summary, author_id, gender_id, year) values ('Dam Busters, The', 'Vinyl', 90, 3, 1981);
insert into books (name, summary, author_id, gender_id, year) values ('Nightmare City (a.k.a. City of the Walking Dead) (a.k.a. Invasión de los zombies atómicos, La) (Incubo sulla città contaminata)', 'Granite', 33, 1, 1981);
insert into books (name, summary, author_id, gender_id, year) values ('Laughing Woman, The (Frightened Woman, The) (Femina ridens)', 'Glass', 77, 2, 1957);
insert into books (name, summary, author_id, gender_id, year) values ('Parisian Love', 'Rubber', 96, 2, 1958);
insert into books (name, summary, author_id, gender_id, year) values ('GLOW: The Story of the Gorgeous Ladies of Wrestling', 'Vinyl', 18, 2, 1964);
insert into books (name, summary, author_id, gender_id, year) values ('Heiress, The', 'Stone', 60, 1, 1989);
insert into books (name, summary, author_id, gender_id, year) values ('Big Fish', 'Granite', 75, 2, 2006);
insert into books (name, summary, author_id, gender_id, year) values ('String, The (Le fil)', 'Stone', 75, 3, 1951);
insert into books (name, summary, author_id, gender_id, year) values ('Honeysuckle Rose (a.k.a. On the Road Again)', 'Brass', 71, 4, 1968);
insert into books (name, summary, author_id, gender_id, year) values ('Hearts and Minds', 'Steel', 8, 1, 2006);
insert into books (name, summary, author_id, gender_id, year) values ('Two Queens and One Consort (Twee vorstinnen en een vorst)', 'Steel', 72, 3, 1987);
insert into books (name, summary, author_id, gender_id, year) values ('Man Made Monster', 'Brass', 85, 2, 2001);
insert into books (name, summary, author_id, gender_id, year) values ('School For Scoundrels', 'Wood', 64, 2, 1934);
insert into books (name, summary, author_id, gender_id, year) values ('Lady Dragon', 'Plastic', 91, 4, 1978);
insert into books (name, summary, author_id, gender_id, year) values ('As I Was Moving Ahead Occasionally I Saw Brief Glimpses of Beauty', 'Aluminum', 34, 2, 1974);
insert into books (name, summary, author_id, gender_id, year) values ('If You Only Knew', 'Vinyl', 74, 3, 2004);
insert into books (name, summary, author_id, gender_id, year) values ('Red Doors', 'Aluminum', 46, 4, 1965);
insert into books (name, summary, author_id, gender_id, year) values ('True Story of Jesse James, The', 'Brass', 8, 2, 1989);
insert into books (name, summary, author_id, gender_id, year) values ('Shape of Things to Come, The', 'Plastic', 8, 2, 1948);
insert into books (name, summary, author_id, gender_id, year) values ('All Passion Spent', 'Glass', 4, 4, 1973);
insert into books (name, summary, author_id, gender_id, year) values ('Daisy Miller', 'Plastic', 46, 4, 2025);
insert into books (name, summary, author_id, gender_id, year) values ('Story of a Love Affair (Cronaca di un amore)', 'Steel', 96, 4, 1962);
insert into books (name, summary, author_id, gender_id, year) values ('Death of a President', 'Brass', 45, 4, 1963);
insert into books (name, summary, author_id, gender_id, year) values ('Winter Passing', 'Rubber', 56, 4, 1982);
insert into books (name, summary, author_id, gender_id, year) values ('Unfinished Business', 'Plastic', 59, 1, 1994);
insert into books (name, summary, author_id, gender_id, year) values ('Valley of Decision, The', 'Granite', 40, 2, 1969);
insert into books (name, summary, author_id, gender_id, year) values ('Major Movie Star', 'Rubber', 77, 4, 2005);
insert into books (name, summary, author_id, gender_id, year) values ('Village People Radio Show (Apa khabar orang kampung)', 'Glass', 73, 1, 1951);
insert into books (name, summary, author_id, gender_id, year) values ('Samurai Assassin (Samurai)', 'Vinyl', 82, 2, 1940);
insert into books (name, summary, author_id, gender_id, year) values ('Oedipus Rex (Edipo re)', 'Steel', 29, 3, 1998);
insert into books (name, summary, author_id, gender_id, year) values ('Dimples', 'Aluminum', 97, 1, 2006);
insert into books (name, summary, author_id, gender_id, year) values ('Until the Light Takes Us', 'Plastic', 91, 2, 2006);
insert into books (name, summary, author_id, gender_id, year) values ('Without Warning (a.k.a. Alien Warning) (a.k.a. It Came Without Warning)', 'Stone', 93, 2, 2018);
